#!/bin/bash

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/root/nodelogic-firstboot.log 2>&1

if [ ! -f "/usr/bin/nodelogic-service-helper.sh" ]; then
	echo "nodelogic-service-helper is missing, cannot continue"
	exit 1
fi

. /usr/bin/nodelogic-service-helper.sh

#when in doubt, let things settle
update_getty "getting things ready"
sleep 30

#we should
update_system
update_getty "configuring system"
configure_nameserver
configure_hosts
configure_sshd
configure_ssh_known_hosts
if [ -f /root/.nodelogic-openstack-controller ]; then
. /usr/bin/nodelogic-openstack-helper.sh
packstack_build
mainevent_apply
configure_final 
fi
if [ -f /root/.nodelogic-docker-portainer ]; then
. /usr/bin/nodelogic-docker-portainer-helper.sh
deploy_traefik
deploy_portainer
fi
branding

systemctl disable nodelogic-firstboot
